//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasySave.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EasySave.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Create backup.
        /// </summary>
        internal static string Button_Create {
            get {
                return ResourceManager.GetString("Button_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete backups.
        /// </summary>
        internal static string Button_Delete {
            get {
                return ResourceManager.GetString("Button_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Execute backups.
        /// </summary>
        internal static string Button_Execute {
            get {
                return ResourceManager.GetString("Button_Execute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Home.
        /// </summary>
        internal static string Button_Home {
            get {
                return ResourceManager.GetString("Button_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Logs.
        /// </summary>
        internal static string Button_Logs {
            get {
                return ResourceManager.GetString("Button_Logs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Quit.
        /// </summary>
        internal static string Button_Quit {
            get {
                return ResourceManager.GetString("Button_Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Settings.
        /// </summary>
        internal static string Button_Settings {
            get {
                return ResourceManager.GetString("Button_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Submit.
        /// </summary>
        internal static string Button_Submit {
            get {
                return ResourceManager.GetString("Button_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error : &apos;{0}&apos;.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Backup &apos;{0}&apos; added successfully..
        /// </summary>
        internal static string Message_AddSuccess {
            get {
                return ResourceManager.GetString("Message_AddSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Business software is running. Please close it before starting a backup..
        /// </summary>
        internal static string Message_BusinessSoftware {
            get {
                return ResourceManager.GetString("Message_BusinessSoftware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Are you sure you want to delete the selected backups?.
        /// </summary>
        internal static string Message_Delete {
            get {
                return ResourceManager.GetString("Message_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Backup &apos;{0}&apos; deleted successfully..
        /// </summary>
        internal static string Message_DeleteSuccess {
            get {
                return ResourceManager.GetString("Message_DeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Directory not found for backup &apos;{0}&apos;..
        /// </summary>
        internal static string Message_DirectoryNotFound {
            get {
                return ResourceManager.GetString("Message_DirectoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Are you sure you want to execute the selected backups?.
        /// </summary>
        internal static string Message_Execute {
            get {
                return ResourceManager.GetString("Message_Execute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Backup &apos;{0}&apos; completed successfully..
        /// </summary>
        internal static string Message_ExecuteSuccess {
            get {
                return ResourceManager.GetString("Message_ExecuteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please fill in all fields..
        /// </summary>
        internal static string Message_Fill {
            get {
                return ResourceManager.GetString("Message_Fill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A backup already has this name..
        /// </summary>
        internal static string Message_NameExists {
            get {
                return ResourceManager.GetString("Message_NameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please select at least one backup..
        /// </summary>
        internal static string Message_Selection {
            get {
                return ResourceManager.GetString("Message_Selection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Backup &apos;{0}&apos; updated successfully..
        /// </summary>
        internal static string Message_UpdateSuccess {
            get {
                return ResourceManager.GetString("Message_UpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Attention.
        /// </summary>
        internal static string MessageTitle_Attention {
            get {
                return ResourceManager.GetString("MessageTitle_Attention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Confirmation.
        /// </summary>
        internal static string MessageTitle_Confirmation {
            get {
                return ResourceManager.GetString("MessageTitle_Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error.
        /// </summary>
        internal static string MessageTitle_Error {
            get {
                return ResourceManager.GetString("MessageTitle_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Succes.
        /// </summary>
        internal static string MessageTitle_Success {
            get {
                return ResourceManager.GetString("MessageTitle_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Backup name.
        /// </summary>
        internal static string Text_BackupName {
            get {
                return ResourceManager.GetString("Text_BackupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date.
        /// </summary>
        internal static string Text_Date {
            get {
                return ResourceManager.GetString("Text_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Encryption time.
        /// </summary>
        internal static string Text_EncryptionTime {
            get {
                return ResourceManager.GetString("Text_EncryptionTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Language.
        /// </summary>
        internal static string Text_Language {
            get {
                return ResourceManager.GetString("Text_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Log Format.
        /// </summary>
        internal static string Text_LogFormat {
            get {
                return ResourceManager.GetString("Text_LogFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modify.
        /// </summary>
        internal static string Text_Modify {
            get {
                return ResourceManager.GetString("Text_Modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Size.
        /// </summary>
        internal static string Text_Size {
            get {
                return ResourceManager.GetString("Text_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Source directory.
        /// </summary>
        internal static string Text_SourceDirectory {
            get {
                return ResourceManager.GetString("Text_SourceDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à State.
        /// </summary>
        internal static string Text_State {
            get {
                return ResourceManager.GetString("Text_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Target directory.
        /// </summary>
        internal static string Text_TargetDirectory {
            get {
                return ResourceManager.GetString("Text_TargetDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Transfert time.
        /// </summary>
        internal static string Text_TransferTime {
            get {
                return ResourceManager.GetString("Text_TransferTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type.
        /// </summary>
        internal static string Text_Type {
            get {
                return ResourceManager.GetString("Text_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Create a backupJob.
        /// </summary>
        internal static string Title_Edit {
            get {
                return ResourceManager.GetString("Title_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Manage file extensions.
        /// </summary>
        internal static string Title_ExtensionsSettings {
            get {
                return ResourceManager.GetString("Title_ExtensionsSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select the backups to modify or execute.
        /// </summary>
        internal static string Title_Home {
            get {
                return ResourceManager.GetString("Title_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Logs.
        /// </summary>
        internal static string Title_Logs {
            get {
                return ResourceManager.GetString("Title_Logs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Saves list.
        /// </summary>
        internal static string Title_SavesList {
            get {
                return ResourceManager.GetString("Title_SavesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Settings.
        /// </summary>
        internal static string Title_Settings {
            get {
                return ResourceManager.GetString("Title_Settings", resourceCulture);
            }
        }
    }
}
