//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasySave.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EasySave.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A backup job with the same name already exists!.
        /// </summary>
        internal static string Error_DuplicateBackupJob {
            get {
                return ResourceManager.GetString("Error_DuplicateBackupJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This field cannot be empty!.
        /// </summary>
        internal static string Error_Empty {
            get {
                return ResourceManager.GetString("Error_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid type!.
        /// </summary>
        internal static string Error_InvalidBackupType {
            get {
                return ResourceManager.GetString("Error_InvalidBackupType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid index: {0}.
        /// </summary>
        internal static string Error_InvalidIndex {
            get {
                return ResourceManager.GetString("Error_InvalidIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid option!.
        /// </summary>
        internal static string Error_InvalidOption {
            get {
                return ResourceManager.GetString("Error_InvalidOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cannot add more than 5 backup jobs!.
        /// </summary>
        internal static string Error_MaxBackupJobs {
            get {
                return ResourceManager.GetString("Error_MaxBackupJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Source directory not found for &apos;{0}&apos;: {1}.
        /// </summary>
        internal static string Error_SourceDirectoryNotFound {
            get {
                return ResourceManager.GetString("Error_SourceDirectoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add a backup Job.
        /// </summary>
        internal static string Menu_AddBackupJob {
            get {
                return ResourceManager.GetString("Menu_AddBackupJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Change language.
        /// </summary>
        internal static string Menu_ChangeLanguage {
            get {
                return ResourceManager.GetString("Menu_ChangeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Change log format.
        /// </summary>
        internal static string Menu_ChangeLogFormat {
            get {
                return ResourceManager.GetString("Menu_ChangeLogFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Change settings.
        /// </summary>
        internal static string Menu_ChangeSettings {
            get {
                return ResourceManager.GetString("Menu_ChangeSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete a backup job.
        /// </summary>
        internal static string Menu_DeleteBackupJob {
            get {
                return ResourceManager.GetString("Menu_DeleteBackupJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Execute a backup.
        /// </summary>
        internal static string Menu_ExecuteBackups {
            get {
                return ResourceManager.GetString("Menu_ExecuteBackups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Quit.
        /// </summary>
        internal static string Menu_Quit {
            get {
                return ResourceManager.GetString("Menu_Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save and return to menu.
        /// </summary>
        internal static string Menu_SaveAndReturn {
            get {
                return ResourceManager.GetString("Menu_SaveAndReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Update a backup job.
        /// </summary>
        internal static string Menu_UpdateBackupJob {
            get {
                return ResourceManager.GetString("Menu_UpdateBackupJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Backup job &apos;{0}&apos; added..
        /// </summary>
        internal static string Message_BackupJobAdded {
            get {
                return ResourceManager.GetString("Message_BackupJobAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Backup job &apos;{0}&apos; deleted..
        /// </summary>
        internal static string Message_BackupJobDeleted {
            get {
                return ResourceManager.GetString("Message_BackupJobDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0}: Name: {1}, Source: {2}, Target: {3}, Type: {4}..
        /// </summary>
        internal static string Message_BackupJobDetails {
            get {
                return ResourceManager.GetString("Message_BackupJobDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Backup job &apos;{0}&apos; executed..
        /// </summary>
        internal static string Message_BackupJobExecuted {
            get {
                return ResourceManager.GetString("Message_BackupJobExecuted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Backup job &apos;{0}&apos; updated..
        /// </summary>
        internal static string Message_BackupJobUpdated {
            get {
                return ResourceManager.GetString("Message_BackupJobUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Language set to &apos;{0}&apos;..
        /// </summary>
        internal static string Message_LanguageSet {
            get {
                return ResourceManager.GetString("Message_LanguageSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Log format set to &apos;{0}&apos;..
        /// </summary>
        internal static string Message_LogFormatSet {
            get {
                return ResourceManager.GetString("Message_LogFormatSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ----- Press ENTER to continue -----.
        /// </summary>
        internal static string Message_PressEnterToContinue {
            get {
                return ResourceManager.GetString("Message_PressEnterToContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Settings saved..
        /// </summary>
        internal static string Message_SettingsSaved {
            get {
                return ResourceManager.GetString("Message_SettingsSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type (Full/Differential): .
        /// </summary>
        internal static string Prompt_BackupType {
            get {
                return ResourceManager.GetString("Prompt_BackupType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choose language (en/fr): .
        /// </summary>
        internal static string Prompt_ChooseLanguage {
            get {
                return ResourceManager.GetString("Prompt_ChooseLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choose log format (json/xml): .
        /// </summary>
        internal static string Prompt_ChooseLogFormat {
            get {
                return ResourceManager.GetString("Prompt_ChooseLogFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choose an option: .
        /// </summary>
        internal static string Prompt_ChooseOption {
            get {
                return ResourceManager.GetString("Prompt_ChooseOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Backup Name: .
        /// </summary>
        internal static string Prompt_JobName {
            get {
                return ResourceManager.GetString("Prompt_JobName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Source directory: .
        /// </summary>
        internal static string Prompt_SourceDirectory {
            get {
                return ResourceManager.GetString("Prompt_SourceDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Target directory: .
        /// </summary>
        internal static string Prompt_TargetDirectory {
            get {
                return ResourceManager.GetString("Prompt_TargetDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ----- Choose backups to execute (e.g., 1,2,3 or 1-3 or all) -----.
        /// </summary>
        internal static string Title_ChooseBackupJobsToExecute {
            get {
                return ResourceManager.GetString("Title_ChooseBackupJobsToExecute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ----- Add a backup job -----.
        /// </summary>
        internal static string Title_ChooseBackupJobToAdd {
            get {
                return ResourceManager.GetString("Title_ChooseBackupJobToAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ----- Delete a backup job -----.
        /// </summary>
        internal static string Title_ChooseBackupJobToDelete {
            get {
                return ResourceManager.GetString("Title_ChooseBackupJobToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ----- Choose backup to update -----.
        /// </summary>
        internal static string Title_ChooseBackupJobToUpdate {
            get {
                return ResourceManager.GetString("Title_ChooseBackupJobToUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ----- Change settings -----.
        /// </summary>
        internal static string Title_ChooseSettingToChange {
            get {
                return ResourceManager.GetString("Title_ChooseSettingToChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ----- MENU -----.
        /// </summary>
        internal static string Title_Menu {
            get {
                return ResourceManager.GetString("Title_Menu", resourceCulture);
            }
        }
    }
}
